# The FreeDOS32 log file writer
# by Salvo Isaja
# ----------------------------------------
# - Use "make" (without arguments) to build the program.
# - "make clean" removes rebuildable files.

fd32log.exe: fd32log.c
	gcc -Wall -O3 -s -o fd32log.exe fd32log.c
	
clean :
	del fd32log.exe

