OBJS    = alloc.o dir.o dos.o file.o open.o volume.o test.o pathreso.o
BIN     = fat
CC      = gcc
#CFLAGS  = -Wall -O3 -I.
CFLAGS  = -Wall -g3 -I.

.PHONY: all clean

all: $(BIN)

clean:
	rm -f $(BIN) $(OBJS)

$(BIN): $(OBJS)
	$(CC) -o $(BIN) $(OBJS) nls/nls.o unicode/unicode.o

%.o: %.c
	$(CC) $(CFLAGS) -c $<
