# FreeDOS-32 Unicode Support Library 2.1
# Makefile for the Linux target

CC = gcc
LD = ld
RM = rm -f

C_OPT    = -Wall -O3
LINK_OPT = -Bstatic -r -s

OBJS   = simple_fold.o utf16le.o utf16be.o utf8.o
OUTLIB = unicode.o
OUTEXE = unicode

all: $(OUTLIB) $(OUTEXE)

clean:
	$(RM) $(OBJS) test.o $(OUTLIB) $(OUTEXE)

$(OUTLIB): $(OBJS)
	$(LD) $(LINK_OPT) $(OBJS) -o $(OUTLIB)

$(OUTEXE): $(OUTLIB) test.o
	$(CC) $(C_OPT) $(OUTLIB) test.o -o $(OUTEXE)

%.o : %.c
	$(CC) $(C_OPT) -c $<
